INSERT INTO `speaker` (`sn`, `name`, `photo`, `title`, `major_related`, `intro`, `fields`) VALUES
(1, '嘉儀', NULL, '', 1, NULL, '0'),
(2, '宅小蛙', NULL, '', 1, NULL, '0'),
(3, 'Mosky', NULL, '', 1, NULL, '0'),
(4, 'Chloe 芝媛', NULL, '', 1, NULL, '0'),
(5, 'Jenny', NULL, '', 1, NULL, '0'),
(6, '依瑪貓', NULL, '', 1, NULL, '0'),
(7, 'Tim', NULL, '', 1, NULL, '0'),
(8, 'Andy Dai', NULL, '', 1, NULL, '0'),
(9, 'Keith', NULL, '', 1, NULL, '0'),
(10, '?', NULL, '', 1, NULL, '0'),
(11, '??', NULL, '', 1, NULL, '0'),
(12, 'Michelle', NULL, '', 1, NULL, '0'),
(13, 'xatier', NULL, '', 1, NULL, '0'),
(14, 'Idee Liao', NULL, '', 1, NULL, '0'),
(15, '小雞', NULL, '', 1, NULL, '0'),
(16, 'Marr', NULL, '', 1, NULL, '0'),
(17, 'JS Girls', NULL, '', 1, NULL, '0'),
(18, 'Sosorry', NULL, '', 1, NULL, '0'),
(19, '蕾咪', NULL, '', 1, NULL, '0'),
(20, '簡璦', NULL, '', 1, NULL, '0'),
(21, '簡薇', NULL, '', 1, NULL, '0'),
(22, '小魚', NULL, '', 1, NULL, '0'),
(23, 'Mars', NULL, '', 1, NULL, '0'),
(24, 'Kelly', NULL, '', 1, NULL, '0'),
(25, '王仲昀', NULL, '', 1, NULL, '0'),
(26, '毛毛', NULL, '', 1, NULL, '0'),
(27, '姿君', NULL, '', 1, NULL, '0'),
(28, '亮亮', NULL, '', 1, NULL, '0'),
(29, 'Share', NULL, '', 1, NULL, '0'),
(30, '柏憲', NULL, '', 1, NULL, '0'),
(31, '佩雯', NULL, '', 1, NULL, '0'),
(32, '新雅', NULL, '', 1, NULL, '0'),
(33, 'plum', NULL, '', 1, NULL, '0'),
(34, '東曄', NULL, '', 1, NULL, '0'),
(35, 'ichi', NULL, '', 1, NULL, '0'),
(36, '家齊', NULL, '', 1, NULL, '0'),
(37, 'Jannya', NULL, '', 1, NULL, '0'),
(38, 'Carol', NULL, '', 1, NULL, '0'),
(39, 'Angie', NULL, '', 1, NULL, '0'),
(40, 'Yi-chu', NULL, '', 1, NULL, '0'),
(41, 'Mia', NULL, '', 1, NULL, '0'),
(42, 'Alicia', NULL, '', 1, NULL, '0'),
(43, '龜珍', NULL, '', 1, NULL, '0'),
(44, '米卡', NULL, '', 1, NULL, '0'),
(45, 'Amber', NULL, '', 1, NULL, '0'),
(46, 'Roxanne', NULL, '', 1, NULL, '0'),
(47, 'UNITA', NULL, '', 1, NULL, '0'),
(48, 'Jamie', NULL, '', 1, NULL, '0'),
(49, 'Youngmi', NULL, '', 1, NULL, '0'),
(50, 'Jane', NULL, '', 1, NULL, '0'),
(51, '小棻', NULL, '', 1, NULL, '0'),
(52, '小蘭', NULL, '', 1, NULL, '0'),
(53, '佳穎 Co Co', NULL, '', 1, '現任職於趨勢科技，擔任資料工程師，工作內容主要是 cloud data infrastructure Integration', '0'),
(54, '苡璇 Jenny', NULL, '', 1, '任職於 KKBOX, 工作為後端開發工程師', '0'),
(55, 'Cicilia Lee', NULL, '', 1, '資料科學家，專長自然語言處理, AI Chatbot', '0');