/*
-- Query: SELECT * FROM pyladies.slide_resource
LIMIT 0, 1000

-- Date: 2019-05-25 10:50
*/
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (1,'slide','Dive into Pinkoi 2013 活動投影片','https://speakerdeck.com/mosky/dive-into-pinkoi-2013');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (2,'slide','活動投影片','https://daikeren.gitbooks.io/python-web-workshop/python_web/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (3,'resource','Code Smart, Don\'t Code hard','https://speakerdeck.com/crboy/code-smart-dont-code-hard');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (4,'resource','ihower 的 Git 教室','https://ihower.tw/git/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (5,'resource','git-scm','https://git-scm.com/book/en/v2');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (6,'resource','GitHub Help','https://help.github.com/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (7,'resource','在koding上搭建爬蟲環境(MySQLdb、lxml、mechanize)','http://tech-marsw.logdown.com/blog/2016/01/25/crawler-how-to-build-environment-on-koding');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (8,'slide','[爬蟲] 教學文','http://tech-marsw.logdown.com/blog/2016/01/10/crawler-index');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (9,'resource','591爬蟲','https://github.com/MarsW/rent_crawler');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (10,'resource','Windows安裝Python+Kivy','http://rasca0027.logdown.com/posts/663370-windows-install-kivy');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (11,'slide','PyLadies Kivy Workshop','https://docs.google.com/presentation/d/1AE9kuARDZAuDuqddSW_vly77nKNs4ijDw2JKbbtD1nk/edit#slide=id.p');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (12,'resource','sample code','https://github.com/rasca0027/pyladies_kivy');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (14,'resource','使用conda安裝pandas','http://conda.pydata.org/miniconda.html');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (15,'slide','Web投影片','https://daikeren.gitbooks.io/python-web-workshop/content/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (16,'slide','Anatomy Of Pandas','https://www.icloud.com/keynote/000aTygxbHa9dvi4t5W9d65Iw#Pandas_Workshop_Complete');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (17,'slide','Kivy投影片','https://www.dropbox.com/s/uvrngt899u546tj/kivy.pptx?dl=0');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (18,'slide','第 1 章 Pythonic 思維','http://tw.pyladies.com/~maomao/1_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (19,'slide','Python基本介紹與第一隻網路爬蟲','https://tw.pyladies.com/~marsw/crawler01.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (22,'slide','常見變數、輸入與輸出、判斷式','https://tw.pyladies.com/~marsw/basic_01.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (23,'slide','迴圈','https://tw.pyladies.com/~marsw/basic_02.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (24,'slide','【教學工作坊】「網路爬蟲」製成術','https://tw.pyladies.com/~marsw/NTHU_workshop.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (25,'slide','第 2 章 函式','http://tw.pyladies.com/~maomao/2_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (26,'slide','更多變數型態、流程敘述回顧、古典加密法','https://tw.pyladies.com/~marsw/basic_03.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (27,'slide','HTML解析、lxml、XPath、檔案IO','https://tw.pyladies.com/~marsw/crawler02.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (29,'slide','排序、函式、字典、檔案IO','https://tw.pyladies.com/~marsw/basic_04.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (31,'slide','第 3 章 類別與繼承','http://tw.pyladies.com/~maomao/3_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (32,'slide','網路爬蟲簡介與實作','https://tw.pyladies.com/~marsw/basic_05.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (33,'slide','活動內容之投影片、Sample Code、環境設定','https://tw.pyladies.com/~marsw/dmworkshop.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (34,'slide','網頁運作原理與爬蟲實作、Cookie、爬蟲實戰技巧','https://tw.pyladies.com/~marsw/crawler03.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (37,'slide','資料庫簡介與規劃','https://tw.pyladies.com/~marsw/basic_06.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (38,'slide','SQLite與Python','https://tw.pyladies.com/~marsw/basic_07.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (39,'slide','第 4 章 元類別與屬性','http://tw.pyladies.com/~maomao/4_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (40,'slide','json、xml、編碼轉換','https://tw.pyladies.com/~marsw/crawler04.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (41,'slide','第 5 章 共時與平行處理','http://tw.pyladies.com/~maomao/5_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (42,'slide','selenium、PhantomJS','https://tw.pyladies.com/~marsw/crawler05.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (43,'slide','第 6 章 內建模組','http://tw.pyladies.com/~maomao/6_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (44,'slide','驗證碼的處理','https://tw.pyladies.com/~marsw/crawler06.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (45,'slide','第 7 章 協作','http://tw.pyladies.com/~maomao/7_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (46,'slide','multi-processing、爬蟲經驗分享','https://tw.pyladies.com/~marsw/crawler07.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (47,'slide','第 8 章 推出產品','http://tw.pyladies.com/~maomao/8_effective_python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (48,'slide','上午場投影片以及下午場分組內容與Sample Code','https://tw.pyladies.com/~marsw/lbworkshop.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (49,'slide','PyLadies 社群運作分享','https://docs.google.com/presentation/d/18YJI03MgMic-0j5NgZRCnU46dBZy-cYc7Dt8lsW-JQ0/edit');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (50,'slide','上午場投影片-Chatbot 種類與技術(高雄)','https://tw.pyladies.com/~marsw/Chatbot-Type.pdf');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (51,'slide','下午場投影片(高雄)','https://tw.pyladies.com/~marsw/linebot_workshop_kg.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (55,'slide','Python基礎語法 與 Line Bot Message Type','https://tw.pyladies.com/~marsw/linebot_workshop_womany_01.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (56,'slide','如何用數據打造最貼心的旅遊搜尋引擎','https://docs.google.com/presentation/d/13OdpytiSowioouyF2XIJr778-mcY3V8FfpKYeSycxsM/edit');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (57,'slide','Python進階資料型別、Google Maps API、api.ai','https://tw.pyladies.com/~marsw/linebot_workshop_womany_02.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (58,'slide','Flask 基礎知識與實作 part 1 - Intro to Flask、First Web App、Template','https://tw.pyladies.com/~maomao/1_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (59,'resource','Nginx + uWSGI 部署Django站點','https://kknews.cc/zh-tw/other/xm99xm9.html');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (60,'resource','uWSGI','https://coder.tw/?p=6375');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (61,'resource','Thread','https://tw.pyladies.com/~maomao/5_effective_python.slides.html#/2/1');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (62,'resource','template、MVC、MVVM概念','http://blog.techbridge.cc/2016/08/27/react-redux-immutablejs-node-server-isomorphic-tutorial/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (63,'slide','物件簡介、判斷式、數值操作','https://tw.pyladies.com/~marsw/book_basic/basic_01.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (65,'slide','字串與序列','https://tw.pyladies.com/~marsw/book_basic/basic_02.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (66,'slide','Python 網路爬蟲入門','https://tw.pyladies.com/~marsw/NKU_python_crawler_basic.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (67,'slide','Flask 基礎知識與實作 part 2 - Template、Web Form、Email','https://tw.pyladies.com/~maomao/2_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (68,'resource','Web 技術中的 Session 是什麼？','http://fred-zone.blogspot.tw/2014/01/web-session.html');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (69,'resource','Cookie & Session','http://tw.pyladies.com/~marsw/crawler03.slides.html#/2');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (70,'slide','序列操作、迴圈','https://tw.pyladies.com/~marsw/book_basic/basic_03.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (71,'slide','迴圈、字典','https://tw.pyladies.com/~marsw/book_basic/basic_04.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (72,'slide','Flask 基礎知識與實作 part 3 - Databases、Large Application Structure','https://tw.pyladies.com/~maomao/3_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (73,'slide','字典與集合','https://tw.pyladies.com/~marsw/book_basic/basic_05.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (75,'slide','data-science-with-python','http://bit.ly/dswpv20171209');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (76,'resource','The Four V\'s of Big Data','https://www.ibmbigdatahub.com/infographic/four-vs-big-data');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (77,'resource','THE FOUR ESSENTIAL V’S FOR A BIG DATA ANALYTICS PLATFORM','http://dataconomy.com/2015/06/the-four-essentials-vs-for-a-big-data-analytics-platform/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (78,'slide','實作部落格程式 part 1 - User Authentication','https://tw.pyladies.com/~maomao/4_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (80,'slide','函式、排序','https://tw.pyladies.com/~marsw/book_basic/basic_06.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (82,'slide','實作部落格程式 part 2 - User Roles、User Profiles、Blog Posts','https://tw.pyladies.com/~maomao/5_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (83,'slide','檔案串流','https://tw.pyladies.com/~marsw/book_basic/basic_07.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (84,'slide','模組','https://tw.pyladies.com/~marsw/book_basic/basic_08.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (85,'slide','實作部落格程式 part 3 - Followers、User Comments、API','https://tw.pyladies.com/~maomao/6_flask.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (86,'slide','異常處理','https://tw.pyladies.com/~marsw/book_basic/basic_09.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (87,'slide','Pinkoi Data Scientist','https://docs.google.com/presentation/d/1NY8stCa7WNTyeVqJs8eNmBTcGWmXSdONjdynvpmXtpg/edit');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (88,'slide','處理 Excel 試算表','https://bijenchen.github.io/PyLadies_Automate_20180429Excel/Day1_Python_Deal_Excel.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (89,'resource','Excel Example @ repl.it','https://repl.it/@MARSW/excelexample');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (90,'slide','Python 基本語法介紹','https://imatcha.github.io/PyLadies/DV_Day1_PyBasic_20180504.html');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (91,'slide','資料視覺化概念介紹','https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-1-concept');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (92,'slide','Python Package','https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-2-plot-packages');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (93,'resource','Code + Notebooks','https://notebooks.azure.com/tsaiichi/libraries/ichi-datavis-2018');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (94,'slide','Dashboard & Kaggle Hands On','https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-3-dashboard');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (95,'resource','PlotDB ','https://plotdb.com/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (96,'slide','Python 工程師的日常小故事與工作應用','https://www.slideshare.net/flywindy/ready-programmer-one-98913870');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (97,'slide','處理CSV檔和JSON資料','https://amberfu.github.io/PyLadies_Automate_JSON_CSV/Day2_Work_with_CSV_files_and_JSON_in_Python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (98,'resource','處理CSV檔和JSON資料-環境設定','https://amberfu.github.io/PyLadies_Automate_JSON_CSV/Day2_Prep.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (99,'resource','OpenWeatherMap','https://openweathermap.org/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (100,'resource','repl.it 教學','https://medium.com/pyladies-taiwan/python-%E7%92%B0%E5%A2%83-repl-it-8b371b128dea');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (101,'slide','Python & NLP','https://drive.google.com/file/d/1KS4PHF8OlmE2ZgUVOAfcRCfOFOiuLYTa/view');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (102,'slide','保持時間、工作排程和程式啟動','https://jamiewei-tw.github.io/PyLadies_AutomateTutorial/Day3_Python_Task_Schedule.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (103,'slide','Sikuli安裝','https://drive.google.com/open?id=14v3vMfUdnXX6cdwVHwqUfXJD8jVTQHhnzPhBc-njNuQ');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (104,'slide','順序性','https://drive.google.com/open?id=1dPsR9qW2y2PBDD2wi1xtwqSvraSqb5SsZsqD39hYONY');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (105,'slide','順序性練習','https://drive.google.com/open?id=1TB0kh7TchoeBZLcONfXd3tmbetBcIyrOfeex8uxOC8A');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (106,'slide','條件判斷','https://drive.google.com/open?id=1LMgD0pMyeIU2ES9RhJBZgrar5qXsumNdmzc4PYPyXlM');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (107,'slide','迴圈','https://drive.google.com/open?id=1szNOWwlrmC6xOg6AexUDSTpY4UWx5YZ_n1mf6gxQdqs');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (108,'slide','除錯練習','https://drive.google.com/open?id=18j6rG3V96rD5XT6XEPEnTpF4BoC5ploIk9VjauD4Egs');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (109,'slide','除錯練習-解答','https://drive.google.com/open?id=1d2GFfa7Bk7WNZSF0reelhIUKwT_Y7g9o');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (110,'slide','成果展說明','https://drive.google.com/open?id=1QmENtG0oKR30Yk9CO1-PKANmrIuqlEl_u3L8_thfKz4');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (111,'slide','投影片技巧','https://drive.google.com/open?id=1zV3x3CHiBeM6PewAo8zI91Ey5Td5IyLn4rixcSliqEo');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (112,'slide','投影片-範例o','https://drive.google.com/open?id=1uVGzMlvKriaJ0ZpwUc0d8p4JFwlYx3DH2xD6__CiYLg');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (113,'slide','投影片-範例x','https://drive.google.com/open?id=1TT2s3tC2FcZcklA8K9HyjXjXSxi7XwTJDzAd_zUG5iE');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (114,'slide','成果展','https://drive.google.com/open?id=10kbCWL0S6Bja0c09Exd3i0d7S7m2CCSJwCL_nPUhBL8');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (115,'resource','更進一步學習','https://drive.google.com/open?id=1dDtnQon5s3ovNdBllGifl2uoEBB7s1m4wUs_1p_DEdw');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (116,'slide','QA 忙什麼 - QA的一天與軟體測試大解析','https://drive.google.com/file/d/1beI-sHZ9XPwfdmqCWw5mO8UWab11QsiL/view');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (117,'slide','發送 Email','https://jamiewei-tw.github.io/PyLadies_AutomateTutorial/Day4_Sending_Email.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (118,'slide','Tensorflow core(需登入才能觀看)','https://hackmd.io/izu41fb9SBqA8OwnrAj8IA?both');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (119,'slide','Model Saving and Profiling(需登入才能觀看)','https://hackmd.io/6dY_0RokS3GiaBSWs_zw5Q?both');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (120,'slide','以 GUI 自動化來控制鍵盤和滑鼠','https://huimi.github.io/Pyladies/Day5_Python_Control_MouseKeyboard.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (121,'resource','以 GUI 自動化來控制鍵盤和滑鼠-環境設定','https://docs.google.com/document/d/10zp11iR5gqUw8v12Ns-Y-ZVoguktQD3KQeZ9ofaiPVI/edit');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (122,'slide','Testing, Environment(需登入才能觀看)','https://hackmd.io/LfJJ43a2QYSnirPV3X7mDg?both');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (123,'resource','demo : mnist-ae','https://github.com/stegben/mnist-ae');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (125,'slide','Serving(需登入才能觀看)','https://hackmd.io/lFhuYTlMSZSXwF8GzXPCrA');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (126,'resource','utilities of tensorflow serving','https://github.com/Yoctol/serving-utils');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (127,'slide','Welcome to PyLadies 5th 周年慶','https://docs.google.com/presentation/d/1XNiq5XttHCaLEuXlk4n0QA7ysE0pYKUQtjs3xyNzMZI/edit#slide=id.g35f391192_00');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (128,'slide','2018 志工報名','https://docs.google.com/forms/d/e/1FAIpQLSdPuFxeVDwDfe2A8L6iS6nvBasq41bXgJY3amZpXL6AnNC64w/viewform');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (129,'slide','School 42 Experience Sharing by Amber','https://speakerdeck.com/pyladiestw/school-42-experience-sharing-by-amber');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (130,'resource','School 42介紹','https://www.twreporter.org/a/france-innovation-education-school-42');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (131,'slide','01 - 程式 與 Python 簡介','https://marsw.github.io/Python-Tutorial/00_intro.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (132,'slide','01 - 常見物件與輸入輸出','https://marsw.github.io/Python-Tutorial/01_basicObject_IO.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (133,'slide','01 - 判斷式','https://marsw.github.io/Python-Tutorial/02_conditional.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (134,'slide','02 - 串列','https://marsw.github.io/Python-Tutorial/03_list.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (135,'slide','02 - 迴圈','https://marsw.github.io/Python-Tutorial/04_loop.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (136,'resource','02 - 序列切片、進階串列存取、更多串列的增刪','https://tw.pyladies.com/~marsw/book_basic/basic_03.slides.html#/3');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (137,'slide','03 - 字典','https://marsw.github.io/Python-Tutorial/05_dictionary.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (138,'slide','03 - Online Judge & 相關查詢資源','https://marsw.github.io/Python-Tutorial/06_onlinejudge_doc.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (139,'slide','04 - 應用','https://marsw.github.io/Python-Tutorial/07_applications.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (140,'slide','04 - 學習資源','https://marsw.github.io/Python-Tutorial/08_resources.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (141,'slide','業界常用工具與技術分享 - PyCharm','https://drive.google.com/file/d/1kkTIrLZ4xHeS019nW73TMmQfrgdS-3fr/view?fbclid=IwAR0cJS-gBROG1BROJe9bdfKsQv-7_txyNrpyh9ofgpNIsDVYRvosxT1Qvlg');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (142,'slide','Git 上半場','https://drive.google.com/file/d/1TW2kp-fMAXFLHRwjb0Z7p7EF2kd2S87u/view?fbclid=IwAR2ap0JC_Nq7nLZmoxugQbaV7w2iRen9hvvxBWunW8u-H-8Fyr1m_dvygP4');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (143,'slide','Git 下半場','https://drive.google.com/file/d/1OCNs6ASq_UDR4pVn9DWd322Fp8N_m4nx/view?fbclid=IwAR1jEs3ZEySK0ewerNYzvpyKz68C4B3MEgisOI5ce7DVvmVxketdDA6f-WA');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (144,'slide','Unit Test in Python for Beginner','https://tw.pyladies.com/~maomao/unit_test/Unit_Test_In_Python.slides.html#/');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (145,'resource','Examples and exercises for Unit Test','https://github.com/win911/UT_class');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (160,'slide','TEST_SLIDE','http://123456');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (161,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (162,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (163,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (164,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (165,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (166,'slide','TEST_SLIDE','http://789101112');
INSERT INTO `slide_resource` (`sn`,`type`,`title`,`url`) VALUES (167,'resource','TEST_Resource','http://8172318294');
