"""empty message

Revision ID: 39ad6fa5fbf0
Revises: 
Create Date: 2018-09-05 08:00:14.126461

"""
from alembic import op
import sqlalchemy as sa

import app


# revision identifiers, used by Alembic.
revision = '39ad6fa5fbf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('addr', sa.String(length=128), nullable=False),
    sa.Column('map', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('major_related', sa.Boolean(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('fields', app.sqldb.models.IntegerArrayType(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('host', sa.Integer(), nullable=False),
    sa.Column('fields', app.sqldb.models.IntegerArrayType(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_basic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('fields', app.sqldb.models.IntegerArrayType(length=128), nullable=False),
    sa.ForeignKeyConstraint(['event_basic_id'], ['event_basic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_basic_id')
    )
    op.create_table('event_info_to_assistant',
    sa.Column('event_info_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['speaker.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_info_id'], ['event_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_info_id', 'assistant_id')
    )
    op.create_table('event_info_to_speaker',
    sa.Column('event_info_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_info_id'], ['event_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_info_id', 'speaker_id')
    )
    op.create_table('slide_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_info_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['event_info_id'], ['event_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slide_resource')
    op.drop_table('event_info_to_speaker')
    op.drop_table('event_info_to_assistant')
    op.drop_table('event_info')
    op.drop_table('link')
    op.drop_table('event_basic')
    op.drop_table('topic')
    op.drop_table('speaker')
    op.drop_table('place')
    # ### end Alembic commands ###
