export default {
  callingAPI: false,
  searching: '',
  serverURI: 'http://10.110.1.136:8080',
  user: null,
  token: null,
  events: [],
  event: [],
  topics: [],
  places: [],
  speakers: [],
  fields: [],
  slide_resources: [],
  post_event_result: null,
  post_place_result: null,
  put_event_result: null,
  put_place_result: null,
  post_slide_result: null,
  log_out_info: null
}
