INSERT INTO `slide_resource` (`sn`, `event_info_sn`, `type`, `title`, `url`) VALUES
(1, 3, 'slide', 'Dive into Pinkoi 2013 活動投影片', 'https://speakerdeck.com/mosky/dive-into-pinkoi-2013'),
(2, 12, 'slide', '活動投影片', 'https://daikeren.gitbooks.io/python-web-workshop/python_web/'),
(3, 13, 'resource', 'Code Smart, Don\'t Code hard', 'https://speakerdeck.com/crboy/code-smart-dont-code-hard'),
(4, 13, 'resource', 'ihower 的 Git 教室', 'https://ihower.tw/git/'),
(5, 13, 'resource', 'git-scm', 'https://git-scm.com/book/en/v2'),
(6, 13, 'resource', 'GitHub Help', 'https://help.github.com/'),
(7, 21, 'resource', '在koding上搭建爬蟲環境(MySQLdb、lxml、mechanize)', 'http://tech-marsw.logdown.com/blog/2016/01/25/crawler-how-to-build-environment-on-koding'),
(8, 21, 'slide', '[爬蟲] 教學文', 'http://tech-marsw.logdown.com/blog/2016/01/10/crawler-index'),
(9, 21, 'resource', '591爬蟲', 'https://github.com/MarsW/rent_crawler'),
(15, 26, 'resource', 'Windows安裝Python+Kivy', 'http://rasca0027.logdown.com/posts/663370-windows-install-kivy'),
(16, 26, 'slide', 'PyLadies Kivy Workshop', 'https://docs.google.com/presentation/d/1AE9kuARDZAuDuqddSW_vly77nKNs4ijDw2JKbbtD1nk/edit#slide=id.p'),
(17, 26, 'resource', 'sample code', 'https://github.com/rasca0027/pyladies_kivy'),
(21, 27, 'resource', 'Windows安裝Python+Kivy', 'http://rasca0027.logdown.com/posts/663370-windows-install-kivy'),
(22, 27, 'resource', '使用conda安裝pandas', 'http://conda.pydata.org/miniconda.html'),
(23, 27, 'slide', 'Web投影片', 'https://daikeren.gitbooks.io/python-web-workshop/content/'),
(24, 27, 'slide', 'Anatomy Of Pandas', 'https://www.icloud.com/keynote/000aTygxbHa9dvi4t5W9d65Iw#Pandas_Workshop_Complete'),
(25, 27, 'slide', 'Kivy投影片', 'https://www.dropbox.com/s/uvrngt899u546tj/kivy.pptx?dl=0'),
(26, 34, 'slide', '第 1 章 Pythonic 思維', 'http://tw.pyladies.com/~maomao/1_effective_python.slides.html#/'),
(27, 42, 'slide', '第 2 章 函式', 'http://tw.pyladies.com/~maomao/2_effective_python.slides.html#/'),
(28, 48, 'slide', '第 3 章 類別與繼承', 'http://tw.pyladies.com/~maomao/3_effective_python.slides.html#/'),
(29, 56, 'slide', '第 4 章 元類別與屬性', 'http://tw.pyladies.com/~maomao/4_effective_python.slides.html#/'),
(30, 58, 'slide', '第 5 章 共時與平行處理', 'http://tw.pyladies.com/~maomao/5_effective_python.slides.html#/'),
(31, 60, 'slide', '第 6 章 內建模組', 'http://tw.pyladies.com/~maomao/6_effective_python.slides.html#/'),
(32, 62, 'slide', '第 7 章 協作', 'http://tw.pyladies.com/~maomao/7_effective_python.slides.html#/'),
(33, 65, 'slide', '第 8 章 推出產品', 'http://tw.pyladies.com/~maomao/8_effective_python.slides.html#/'),
(34, 35, 'slide', 'Python基本介紹與第一隻網路爬蟲', 'https://tw.pyladies.com/~marsw/crawler01.slides.html#/'),
(35, 36, 'slide', 'Python基本介紹與第一隻網路爬蟲', 'https://tw.pyladies.com/~marsw/crawler01.slides.html#/'),
(36, 37, 'slide', 'Python基本介紹與第一隻網路爬蟲', 'https://tw.pyladies.com/~marsw/crawler01.slides.html#/'),
(37, 44, 'slide', 'HTML解析、lxml、XPath、檔案IO', 'https://tw.pyladies.com/~marsw/crawler02.slides.html#/'),
(38, 45, 'slide', 'HTML解析、lxml、XPath、檔案IO', 'https://tw.pyladies.com/~marsw/crawler02.slides.html#/'),
(39, 47, 'slide', 'HTML解析、lxml、XPath、檔案IO', 'https://tw.pyladies.com/~marsw/crawler02.slides.html#/'),
(40, 51, 'slide', '網頁運作原理與爬蟲實作、Cookie、爬蟲實戰技巧', 'https://tw.pyladies.com/~marsw/crawler03.slides.html#/'),
(41, 52, 'slide', '網頁運作原理與爬蟲實作、Cookie、爬蟲實戰技巧', 'https://tw.pyladies.com/~marsw/crawler03.slides.html#/'),
(42, 53, 'slide', '網頁運作原理與爬蟲實作、Cookie、爬蟲實戰技巧', 'https://tw.pyladies.com/~marsw/crawler03.slides.html#/'),
(43, 57, 'slide', 'json、xml、編碼轉換', 'https://tw.pyladies.com/~marsw/crawler04.slides.html#/'),
(44, 59, 'slide', 'selenium、PhantomJS', 'https://tw.pyladies.com/~marsw/crawler05.slides.html#/'),
(45, 61, 'slide', '驗證碼的處理', 'https://tw.pyladies.com/~marsw/crawler06.slides.html#/'),
(46, 63, 'slide', 'multi-processing、爬蟲經驗分享', 'https://tw.pyladies.com/~marsw/crawler07.slides.html#/'),
(47, 38, 'slide', '常見變數、輸入與輸出、判斷式', 'https://tw.pyladies.com/~marsw/basic_01.slides.html#/'),
(48, 39, 'slide', '迴圈', 'https://tw.pyladies.com/~marsw/basic_02.slides.html#/'),
(49, 43, 'slide', '更多變數型態、流程敘述回顧、古典加密法', 'https://tw.pyladies.com/~marsw/basic_03.slides.html#/'),
(50, 46, 'slide', '排序、函式、字典、檔案IO', 'https://tw.pyladies.com/~marsw/basic_04.slides.html#/'),
(51, 49, 'slide', '網路爬蟲簡介與實作', 'https://tw.pyladies.com/~marsw/basic_05.slides.html#/'),
(52, 54, 'slide', '資料庫簡介與規劃', 'https://tw.pyladies.com/~marsw/basic_06.slides.html#/'),
(53, 55, 'slide', 'SQLite與Python', 'https://tw.pyladies.com/~marsw/basic_07.slides.html#/'),
(54, 41, 'slide', '【教學工作坊】「網路爬蟲」製成術', 'https://tw.pyladies.com/~marsw/NTHU_workshop.slides.html#/'),
(55, 50, 'slide', '活動內容之投影片、Sample Code、環境設定', 'https://tw.pyladies.com/~marsw/dmworkshop.slides.html#/'),
(56, 66, 'slide', '上午場投影片以及下午場分組內容與Sample Code', 'https://tw.pyladies.com/~marsw/lbworkshop.slides.html#/'),
(57, 68, 'slide', '上午場投影片-Chatbot 種類與技術(高雄)', 'https://tw.pyladies.com/~marsw/Chatbot-Type.pdf'),
(58, 68, 'slide', '下午場投影片(高雄)', 'https://tw.pyladies.com/~marsw/linebot_workshop_kg.slides.html#/'),
(59, 67, 'slide', 'PyLadies 社群運作分享', 'https://docs.google.com/presentation/d/18YJI03MgMic-0j5NgZRCnU46dBZy-cYc7Dt8lsW-JQ0/edit'),
(60, 73, 'slide', 'Python基本介紹與第一隻網路爬蟲', 'https://tw.pyladies.com/~marsw/crawler01.slides.html#/'),
(61, 74, 'slide', 'HTML簡介與解析', 'https://tw.pyladies.com/~marsw/crawler02.slides.html#/'),
(62, 75, 'slide', '網頁運作原理說明與爬蟲實例解析', 'https://tw.pyladies.com/~marsw/crawler03.slides.html#/'),
(63, 77, 'slide', 'Python基礎語法 與 Line Bot Message Type', 'https://tw.pyladies.com/~marsw/linebot_workshop_womany_01.slides.html#/'),
(64, 79, 'slide', 'Python進階資料型別、Google Maps API、api.ai', 'https://tw.pyladies.com/~marsw/linebot_workshop_womany_02.slides.html#/'),
(65, 78, 'slide', '如何用數據打造最貼心的旅遊搜尋引擎', 'https://docs.google.com/presentation/d/13OdpytiSowioouyF2XIJr778-mcY3V8FfpKYeSycxsM/edit'),
(66, 82, 'slide', '如何用數據打造最貼心的旅遊搜尋引擎', 'https://docs.google.com/presentation/d/13OdpytiSowioouyF2XIJr778-mcY3V8FfpKYeSycxsM/edit'),
(67, 80, 'slide', 'Flask 基礎知識與實作 part 1 - Intro to Flask、First Web App、Template', 'https://tw.pyladies.com/~maomao/1_flask.slides.html#/'),
(68, 86, 'slide', 'Flask 基礎知識與實作 part 2 - Template、Web Form、Email', 'https://tw.pyladies.com/~maomao/2_flask.slides.html#/'),
(69, 89, 'slide', 'Flask 基礎知識與實作 part 3 - Databases、Large Application Structure', 'https://tw.pyladies.com/~maomao/3_flask.slides.html#/'),
(70, 93, 'slide', '實作部落格程式 part 1 - User Authentication', 'https://tw.pyladies.com/~maomao/4_flask.slides.html#/'),
(71, 97, 'slide', '實作部落格程式 part 2 - User Roles、User Profiles、Blog Posts', 'https://tw.pyladies.com/~maomao/5_flask.slides.html#/'),
(72, 100, 'slide', '實作部落格程式 part 3 - Followers、User Comments、API', 'https://tw.pyladies.com/~maomao/6_flask.slides.html#/'),
(74, 80, 'resource', 'Nginx + uWSGI 部署Django站點', 'https://kknews.cc/zh-tw/other/xm99xm9.html'),
(75, 80, 'resource', 'uWSGI', 'https://coder.tw/?p=6375'),
(76, 80, 'resource', 'Thread', 'https://tw.pyladies.com/~maomao/5_effective_python.slides.html#/2/1'),
(77, 80, 'resource', 'template、MVC、MVVM概念', 'http://blog.techbridge.cc/2016/08/27/react-redux-immutablejs-node-server-isomorphic-tutorial/'),
(79, 86, 'resource', 'Web 技術中的 Session 是什麼？', 'http://fred-zone.blogspot.tw/2014/01/web-session.html'),
(80, 86, 'resource', 'Cookie & Session', 'http://tw.pyladies.com/~marsw/crawler03.slides.html#/2'),
(81, 81, 'slide', '物件簡介、判斷式、數值操作', 'https://tw.pyladies.com/~marsw/book_basic/basic_01.slides.html#/'),
(82, 84, 'slide', '字串與序列', 'https://tw.pyladies.com/~marsw/book_basic/basic_02.slides.html#/'),
(83, 87, 'slide', '序列操作、迴圈', 'https://tw.pyladies.com/~marsw/book_basic/basic_03.slides.html#/'),
(84, 88, 'slide', '迴圈、字典', 'https://tw.pyladies.com/~marsw/book_basic/basic_04.slides.html#/'),
(85, 90, 'slide', '字典與集合', 'https://tw.pyladies.com/~marsw/book_basic/basic_05.slides.html#/'),
(86, 95, 'slide', '函式、排序', 'https://tw.pyladies.com/~marsw/book_basic/basic_06.slides.html#/'),
(87, 98, 'slide', '檔案串流', 'https://tw.pyladies.com/~marsw/book_basic/basic_07.slides.html#/'),
(88, 99, 'slide', '模組', 'https://tw.pyladies.com/~marsw/book_basic/basic_08.slides.html#/'),
(89, 101, 'slide', '異常處理', 'https://tw.pyladies.com/~marsw/book_basic/basic_09.slides.html#/'),
(90, 85, 'slide', 'Python 網路爬蟲入門', 'https://tw.pyladies.com/~marsw/NKU_python_crawler_basic.slides.html#/'),
(91, 91, 'slide', 'selenium、PhantomJS', 'https://tw.pyladies.com/~marsw/crawler05.slides.html#/'),
(92, 92, 'slide', 'data-science-with-python', 'http://bit.ly/dswpv20171209'),
(93, 92, 'resource', 'The Four V\'s of Big Data', 'https://www.ibmbigdatahub.com/infographic/four-vs-big-data'),
(94, 92, 'resource', 'THE FOUR ESSENTIAL V’S FOR A BIG DATA ANALYTICS PLATFORM', 'http://dataconomy.com/2015/06/the-four-essentials-vs-for-a-big-data-analytics-platform/'),
(95, 94, 'slide', 'data-science-with-python', 'http://bit.ly/dswpv20171209'),
(96, 96, 'slide', 'data-science-with-python', 'http://bit.ly/dswpv20171209'),
(97, 103, 'slide', 'Pinkoi Data Scientist', 'https://docs.google.com/presentation/d/1NY8stCa7WNTyeVqJs8eNmBTcGWmXSdONjdynvpmXtpg/edit'),
(98, 109, 'slide', 'Python 工程師的日常小故事與工作應用', 'https://www.slideshare.net/flywindy/ready-programmer-one-98913870'),
(99, 111, 'slide', 'Python & NLP', 'https://drive.google.com/file/d/1KS4PHF8OlmE2ZgUVOAfcRCfOFOiuLYTa/view'),
(100, 116, 'slide', 'QA 忙什麼 - QA的一天與軟體測試大解析', 'https://drive.google.com/file/d/1beI-sHZ9XPwfdmqCWw5mO8UWab11QsiL/view'),
(101, 104, 'slide', '處理 Excel 試算表', 'https://bijenchen.github.io/PyLadies_Automate_20180429Excel/Day1_Python_Deal_Excel.slides.html#/'),
(102, 104, 'resource', 'Excel Example @ repl.it', 'https://repl.it/@MARSW/excelexample'),
(103, 110, 'slide', '處理CSV檔和JSON資料', 'https://amberfu.github.io/PyLadies_Automate_JSON_CSV/Day2_Work_with_CSV_files_and_JSON_in_Python.slides.html#/'),
(104, 110, 'resource', '處理CSV檔和JSON資料-環境設定', 'https://amberfu.github.io/PyLadies_Automate_JSON_CSV/Day2_Prep.slides.html#/'),
(105, 110, 'resource', 'OpenWeatherMap', 'https://openweathermap.org/'),
(106, 110, 'resource', 'repl.it 教學', 'https://medium.com/pyladies-taiwan/python-%E7%92%B0%E5%A2%83-repl-it-8b371b128dea'),
(107, 112, 'slide', '保持時間、工作排程和程式啟動', 'https://jamiewei-tw.github.io/PyLadies_AutomateTutorial/Day3_Python_Task_Schedule.slides.html#/'),
(108, 117, 'slide', '發送 Email', 'https://jamiewei-tw.github.io/PyLadies_AutomateTutorial/Day4_Sending_Email.slides.html#/'),
(109, 121, 'slide', '以 GUI 自動化來控制鍵盤和滑鼠', 'https://huimi.github.io/Pyladies/Day5_Python_Control_MouseKeyboard.slides.html#/'),
(110, 121, 'resource', '以 GUI 自動化來控制鍵盤和滑鼠-環境設定', 'https://docs.google.com/document/d/10zp11iR5gqUw8v12Ns-Y-ZVoguktQD3KQeZ9ofaiPVI/edit'),
(111, 105, 'slide', 'Python 基本語法介紹', 'https://imatcha.github.io/PyLadies/DV_Day1_PyBasic_20180504.html'),
(112, 106, 'slide', '資料視覺化概念介紹', 'https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-1-concept'),
(113, 107, 'slide', 'Python Package', 'https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-2-plot-packages'),
(114, 107, 'resource', 'Code + Notebooks', 'https://notebooks.azure.com/tsaiichi/libraries/ichi-datavis-2018'),
(115, 108, 'slide', 'Dashboard & Kaggle Hands On', 'https://www.slideshare.net/YiChihTsai2/aic-x-pyladies-tw-python-data-vis-3-dashboard'),
(116, 108, 'resource', 'PlotDB ', 'https://plotdb.com/'),
(117, 113, 'slide', 'Sikuli安裝', 'https://drive.google.com/open?id=14v3vMfUdnXX6cdwVHwqUfXJD8jVTQHhnzPhBc-njNuQ'),
(118, 113, 'slide', '順序性', 'https://drive.google.com/open?id=1dPsR9qW2y2PBDD2wi1xtwqSvraSqb5SsZsqD39hYONY'),
(119, 113, 'slide', '順序性練習', 'https://drive.google.com/open?id=1TB0kh7TchoeBZLcONfXd3tmbetBcIyrOfeex8uxOC8A'),
(120, 113, 'slide', '條件判斷', 'https://drive.google.com/open?id=1LMgD0pMyeIU2ES9RhJBZgrar5qXsumNdmzc4PYPyXlM'),
(121, 114, 'slide', '迴圈', 'https://drive.google.com/open?id=1szNOWwlrmC6xOg6AexUDSTpY4UWx5YZ_n1mf6gxQdqs'),
(122, 114, 'slide', '除錯練習', 'https://drive.google.com/open?id=18j6rG3V96rD5XT6XEPEnTpF4BoC5ploIk9VjauD4Egs'),
(123, 114, 'slide', '除錯練習-解答', 'https://drive.google.com/open?id=1d2GFfa7Bk7WNZSF0reelhIUKwT_Y7g9o'),
(124, 114, 'slide', '成果展說明', 'https://drive.google.com/open?id=1QmENtG0oKR30Yk9CO1-PKANmrIuqlEl_u3L8_thfKz4'),
(125, 115, 'slide', '投影片技巧', 'https://drive.google.com/open?id=1zV3x3CHiBeM6PewAo8zI91Ey5Td5IyLn4rixcSliqEo'),
(126, 115, 'slide', '投影片-範例o', 'https://drive.google.com/open?id=1uVGzMlvKriaJ0ZpwUc0d8p4JFwlYx3DH2xD6__CiYLg'),
(127, 115, 'slide', '投影片-範例x', 'https://drive.google.com/open?id=1TT2s3tC2FcZcklA8K9HyjXjXSxi7XwTJDzAd_zUG5iE'),
(128, 115, 'slide', '成果展', 'https://drive.google.com/open?id=10kbCWL0S6Bja0c09Exd3i0d7S7m2CCSJwCL_nPUhBL8'),
(129, 115, 'resource', '更進一步學習', 'https://drive.google.com/open?id=1dDtnQon5s3ovNdBllGifl2uoEBB7s1m4wUs_1p_DEdw'),
(130, 118, 'slide', 'Tensorflow core(需登入才能觀看)', 'https://hackmd.io/izu41fb9SBqA8OwnrAj8IA?both'),
(131, 120, 'slide', 'Model Saving and Profiling(需登入才能觀看)', 'https://hackmd.io/6dY_0RokS3GiaBSWs_zw5Q?both'),
(132, 122, 'slide', 'Testing, Environment(需登入才能觀看)', 'https://hackmd.io/LfJJ43a2QYSnirPV3X7mDg?both'),
(133, 122, 'resource', 'demo : mnist-ae', 'https://github.com/stegben/mnist-ae'),
(134, 123, 'slide', 'Serving(需登入才能觀看)', 'https://hackmd.io/lFhuYTlMSZSXwF8GzXPCrA'),
(135, 123, 'resource', 'utilities of tensorflow serving', 'https://github.com/Yoctol/serving-utils'),
(136, 123, 'resource', 'sample code : mnist-ae', 'https://github.com/stegben/mnist-ae'),
(140, 124, 'slide', 'Welcome to PyLadies 5th 周年慶', 'https://docs.google.com/presentation/d/1XNiq5XttHCaLEuXlk4n0QA7ysE0pYKUQtjs3xyNzMZI/edit#slide=id.g35f391192_00'),
(141, 124, 'slide', '2018 志工報名', 'https://docs.google.com/forms/d/e/1FAIpQLSdPuFxeVDwDfe2A8L6iS6nvBasq41bXgJY3amZpXL6AnNC64w/viewform'),
(142, 124, 'slide', 'School 42 Experience Sharing by Amber', 'https://speakerdeck.com/pyladiestw/school-42-experience-sharing-by-amber'),
(143, 124, 'resource', 'School 42介紹', 'https://www.twreporter.org/a/france-innovation-education-school-42'),
(144, 125, 'slide', '01 - 程式 與 Python 簡介', 'https://marsw.github.io/Python-Tutorial/00_intro.slides.html#/'),
(145, 125, 'slide', '01 - 常見物件與輸入輸出', 'https://marsw.github.io/Python-Tutorial/01_basicObject_IO.slides.html#/'),
(146, 125, 'slide', '01 - 判斷式', 'https://marsw.github.io/Python-Tutorial/02_conditional.slides.html#/'),
(147, 126, 'slide', '02 - 串列', 'https://marsw.github.io/Python-Tutorial/03_list.slides.html#/'),
(148, 126, 'slide', '02 - 迴圈', 'https://marsw.github.io/Python-Tutorial/04_loop.slides.html#/'),
(149, 126, 'resource', '02 - 序列切片、進階串列存取、更多串列的增刪', 'https://tw.pyladies.com/~marsw/book_basic/basic_03.slides.html#/3'),
(150, 127, 'slide', '03 - 字典', 'https://marsw.github.io/Python-Tutorial/05_dictionary.slides.html#/'),
(151, 127, 'slide', '03 - Online Judge & 相關查詢資源', 'https://marsw.github.io/Python-Tutorial/06_onlinejudge_doc.slides.html#/'),
(152, 128, 'slide', '04 - 應用', 'https://marsw.github.io/Python-Tutorial/07_applications.slides.html#/'),
(153, 128, 'slide', '04 - 學習資源', 'https://marsw.github.io/Python-Tutorial/08_resources.slides.html#/'),
(154, 146, 'slide', '業界常用工具與技術分享 - PyCharm', 'https://drive.google.com/file/d/1kkTIrLZ4xHeS019nW73TMmQfrgdS-3fr/view?fbclid=IwAR0cJS-gBROG1BROJe9bdfKsQv-7_txyNrpyh9ofgpNIsDVYRvosxT1Qvlg'),
(156, 147, 'slide', 'Git 上半場', 'https://drive.google.com/file/d/1TW2kp-fMAXFLHRwjb0Z7p7EF2kd2S87u/view?fbclid=IwAR2ap0JC_Nq7nLZmoxugQbaV7w2iRen9hvvxBWunW8u-H-8Fyr1m_dvygP4'),
(157, 147, 'slide', 'Git 下半場', 'https://drive.google.com/file/d/1OCNs6ASq_UDR4pVn9DWd322Fp8N_m4nx/view?fbclid=IwAR1jEs3ZEySK0ewerNYzvpyKz68C4B3MEgisOI5ce7DVvmVxketdDA6f-WA'),
(158, 148, 'slide', 'Unit Test in Python for Beginner', 'https://tw.pyladies.com/~maomao/unit_test/Unit_Test_In_Python.slides.html#/'),
(159, 148, 'resource', 'Examples and exercises for Unit Test', 'https://github.com/win911/UT_class');